import Head from 'next/head';

export default function NotWorking() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-full">
        <section className="sm:py-24 lg:py-32 py-12">
          <div className="mx-auto max-w-2xl px-4 sm:px-6 lg:max-w-7xl">
            <p>
              Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ipsam,
              nam.
            </p>
          </div>
        </section>
      </main>
    </>
  );
}
